version: '3'

tasks:
  # ---------- Test Tasks ----------
  test:
    desc: "Unit Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME="Unit Tests" c8 --report-dir='coverage/unit' mocha 'test/unit/**/*.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit.xml

  test-e2e-all:
    desc: "Mocha E2E All Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME="Mocha E2E All Tests" c8 --report-dir='coverage/e2e-all' mocha 'test/e2e/**/*.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-all.xml

  test-e2e-integration:
    desc: "Mocha E2E Integration Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME="Mocha E2E Integration Tests" c8 --report-dir='coverage/e2e-integration' mocha 'test/e2e/integration/**/*.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-integration.xml

  test-e2e-standard:
    desc: "Mocha E2E Standard Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME="Mocha E2E Standard Tests" c8 --report-dir='coverage/e2e-standard' mocha 'test/e2e/**/*.ts' --ignore 'test/unit/**/*.ts' --ignore 'test/e2e/integration/**/*.ts' --ignore 'test/e2e/commands/mirror_node*.ts' --ignore 'test/e2e/commands/node*.ts' --ignore 'test/e2e/commands/separate_node*.ts' --ignore 'test/e2e/commands/relay*.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-standard.xml --timeout 30000

  test-e2e-mirror-node:
    desc: "Mocha E2E Mirror Node Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Mirror Node Tests\" c8 --report-dir='coverage/e2e-mirror-node' mocha 'test/e2e/commands/mirror_node.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-mirror-node.xml

  test-e2e-node-pem-stop:
    desc: "Mocha E2E Node PEM Stop Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Node PEM Stop Tests\" c8 --report-dir='coverage/e2e-node-pem-stop' mocha 'test/e2e/commands/node_pem_stop.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-node-pem-stop.xml

  test-e2e-node-pem-kill:
    desc: "Mocha E2E Node PEM Kill Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Node PEM Kill Tests\" c8 --report-dir='coverage/e2e-node-pem-kill' mocha 'test/e2e/commands/node_pem_kill.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-node-pem-kill.xml

  test-e2e-node-local-hedera:
    desc: "Mocha E2E Node Local Hedera Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Node Local Hedera Tests\" c8 --report-dir='coverage/e2e-node-local-hedera' mocha 'test/e2e/commands/node_local_hedera.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-node-local-hedera.xml

  test-e2e-node-local-ptt:
    desc: "Mocha E2E Node Local PTT Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Node Local PTT Tests\" c8 --report-dir='coverage/e2e-node-local-ptt' mocha 'test/e2e/commands/node_local_ptt.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-node-local-ptt.xml

  test-e2e-node-add:
    desc: "Mocha E2E Node Add Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Node Add Tests\" c8 --report-dir='coverage/e2e-node-add' mocha 'test/e2e/commands/node_add.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-node-add.xml

  test-e2e-node-add-local:
    desc: "Mocha E2E Node Add Local Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Node Add Local Tests\" c8 --report-dir='coverage/e2e-node-add-local' mocha 'test/e2e/commands/node_add_local.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-node-add-local.xml

  test-e2e-node-add-separate-commands:
    desc: "Mocha E2E Node Add - Separate commands Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Node Add - Separate commands Tests\" c8 --report-dir='coverage/e2e-node-add-separate-commands' mocha 'test/e2e/commands/separate_node_add*.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-node-add-separate-commands.xml

  test-e2e-node-update:
    desc: "Mocha E2E Node Update Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Node Update Tests\" c8 --report-dir='coverage/e2e-node-update' mocha 'test/e2e/commands/node_update*.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-node-update.xml

  test-e2e-node-update-separate-commands:
    desc: "Mocha E2E Node Update - Separate commands Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Node Update - Separate commands Tests\" c8 --report-dir='coverage/e2e-node-update-separate-commands' mocha 'test/e2e/commands/separate_node_update.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-node-update-separate-commands.xml

  test-e2e-node-delete:
    desc: "Mocha E2E Node Delete Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Node Delete Tests\" c8 --report-dir='coverage/e2e-node-delete' mocha 'test/e2e/commands/node_delete*.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-node-delete.xml

  test-e2e-node-delete-separate-commands:
    desc: "Mocha E2E Node Delete - Separate commands Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Node Delete - Separate commands Tests\" c8 --report-dir='coverage/e2e-node-delete-separate-commands' mocha 'test/e2e/commands/separate_node_delete*.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-node-delete-separate-commands.xml

  test-e2e-node-upgrade:
    desc: "Mocha E2E Node Upgrade Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Node Upgrade Tests\" c8 --report-dir='coverage/e2e-node-upgrade' mocha 'test/e2e/commands/node_upgrade*.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-node-upgrade.xml

  test-e2e-relay:
    desc: "Mocha E2E Relay Tests"
    cmds:
      - cross-env MOCHA_SUITE_NAME=\"Mocha E2E Relay Tests\" c8 --report-dir='coverage/e2e-relay' mocha 'test/e2e/commands/relay.test.ts' --reporter-options configFile=mocha-multi-reporter.json,cmrOutput=mocha-junit-reporter+mochaFile+junit-e2e-relay.xml

  test-example-taskfile:
    desc: "Test Example Taskfile"
    cmds:
      - task --taskfile examples/custom-network-config/Taskfile.yml -d . default

  # ---------- CLI Execution commands ----------

  solo-test:
    cmds:
      - node --no-deprecation --no-warnings --loader ts-node/esm solo.ts

  solo:
    cmds:
      - node --no-deprecation --no-warnings dist/solo.js

  # ---------- Lint and format tasks ----------

  check:
    cmds:
      - remark . --quiet --frail && eslint . --ignore-pattern 'docs/*' --ignore-pattern 'dist/*'; cd docs; jsdoc -c jsdoc.conf.json && tsc

  format:
    cmds:
      - remark . --quiet --frail --output && eslint --fix . --ignore-pattern 'docs/*' --ignore-pattern 'dist/*'

  # Setup, build, and miscellaneous tasks

  test-setup:
    cmds:
      - ./test/e2e/setup-e2e.sh

  build:
    cmds:
      - swc src version.ts solo.ts -d dist && node resources/post-build-script.js
