baseURL = 'https://solo.hiero.org/'
languageCode = 'en-us'
title = 'Solo'
theme = "hugo-geekdoc"

# Required if you want to render robots.txt template
enableRobotsTXT = true

[params]
# (Optional, default false) Render menu from data file in 'data/menu/main.yaml'.
# See also https://geekdocs.de/usage/menus/#bundle-menu.
geekdocCollapseMenu = true
geekdocMenuBundle = true  # This ensures menu items from config.toml are used
