version: 3
env:
  SOLO_DEPLOYMENT: "nested-cluster-deployment"
  SOLO_NAMESPACE: "nested-cluster-namespace"
  SOLO_CLUSTER_NAME: "nested-cluster-cluster"
tasks:
  start:
    cmds:
      - mkdir -p {{.TASKFILE_DIR}}/.task-tmp
      - mkdir -p {{.TASKFILE_DIR}}/.task-tmp
      - envsubst < {{.TASKFILE_DIR}}/templates/sa-admin.yaml.tmpl > {{.TASKFILE_DIR}}/.task-tmp/sa-admin.yaml
      - mkdir -p {{.TASKFILE_DIR}}/.task-tmp
      - envsubst < {{.TASKFILE_DIR}}/templates/ubuntu-privileged-pod.yaml.tmpl > {{.TASKFILE_DIR}}/.task-tmp/ubuntu-privileged-pod.yaml
      - kubectl apply -f {{.TASKFILE_DIR}}/.task-tmp/sa-admin.yaml
      - kubectl apply -f {{.TASKFILE_DIR}}/.task-tmp/ubuntu-privileged-pod.yaml

      # Wait for the pod to be ready
      - kubectl wait --for=condition=Ready pod/ubuntu-priv -n solo-e2e --timeout=120s

      # Copy the environment setup script to /root inside the pod
      - kubectl cp {{.TASKFILE_DIR}}/scripts/setup-environment.sh solo-e2e/ubuntu-priv:/root/setup-environment.sh

      # Change permission to executable inside the pod
      - kubectl exec -n solo-e2e ubuntu-priv -- chmod +x /root/setup-environment.sh

      # Run the script to setup the environment inside the pod
      - kubectl exec -n solo-e2e ubuntu-priv -- sh -c "SOLO_DEPLOYMENT={{.SOLO_DEPLOYMENT}} SOLO_NAMESPACE={{.SOLO_NAMESPACE}} SOLO_CLUSTER_NAME={{.SOLO_CLUSTER_NAME}} /root/setup-environment.sh"
    # ...existing code...
  cleanup:
    desc: Delete the privileged pod and ServiceAccount used for the test
    cmds:
      - kubectl delete pod ubuntu-privileged-pod || true
      - kubectl delete sa solo-admin || true
