version: 3

# This Taskfile creates a Hiero deployment with a block node using Kind and kubectl.

vars:
  NODE_IDENTIFIERS: "node1"
  BLOCK_NODE_RELEASE_TAG: "v0.62.6"
  SOLO_NETWORK_SIZE: "1"
  DEPLOYMENT: "deployment-network-with-block-node"
  NAMESPACE: "namespace-network-with-block-node"
  CLUSTER_NAME: "solo-cluster"
  CONTEXT: "kind-solo-cluster"
  CLUSTER_REFERENCE: "kind-solo-cluster"
tasks:
  install:
    desc: Run a full standalone Solo network with block node, mirror node, and relay
    cmds:
      - npm i @hashgraph/solo
      - kind create cluster -n {{ .CLUSTER_NAME }}
      - sleep 10 # wait for control plane to come up
      - kubectl config set-context {{ .CONTEXT }}
      - solo init
      - solo cluster-ref connect --cluster-ref {{ .CLUSTER_REFERENCE }} --context {{ .CONTEXT }}
      - solo deployment create --deployment {{ .DEPLOYMENT }} --namespace {{ .NAMESPACE }}
      - solo deployment add-cluster --deployment {{ .DEPLOYMENT }} --cluster-ref {{ .CLUSTER_REFERENCE }} --num-consensus-nodes {{ .SOLO_NETWORK_SIZE }}
      - solo cluster-ref setup --cluster-ref {{ .CLUSTER_REFERENCE }}
      - solo block node add --deployment {{ .DEPLOYMENT }} --release-tag {{ .BLOCK_NODE_RELEASE_TAG }} --cluster-ref {{ .CLUSTER_REFERENCE }}
      - solo node keys --gossip-keys --tls-keys --deployment {{ .DEPLOYMENT }} --pvcs true --node-aliases {{ .NODE_IDENTIFIERS }}
      - solo network deploy --deployment {{ .DEPLOYMENT }} --pvcs true --node-aliases {{ .NODE_IDENTIFIERS }}
      - solo node setup --node-aliases {{ .NODE_IDENTIFIERS }} --deployment {{ .DEPLOYMENT }}
      - solo node start --deployment {{ .DEPLOYMENT }} --node-aliases {{ .NODE_IDENTIFIERS }}
      - solo mirror-node deploy --deployment {{ .DEPLOYMENT }} --pinger
      - solo relay deploy --deployment {{ .DEPLOYMENT }} --node-aliases {{ .NODE_IDENTIFIERS }}
      - solo explorer deploy --deployment {{ .DEPLOYMENT }} --cluster-ref {{ .CLUSTER_REFERENCE }}
  destroy:
    desc: Destroy the Solo network with block node
    cmds:
      - solo node stop --deployment {{ .DEPLOYMENT }} --node-aliases {{ .NODE_IDENTIFIERS }}
      - solo mirror-node destroy --deployment {{ .DEPLOYMENT }} --force
      - solo relay destroy --deployment {{ .DEPLOYMENT }} --node-aliases {{ .NODE_IDENTIFIERS }}
      - solo explorer destroy --deployment {{ .DEPLOYMENT }}
      - solo network destroy --deployment {{ .DEPLOYMENT }} --force
      - kind delete cluster -n {{ .CLUSTER_NAME }}