name: Zip and Upload Examples

on:
  workflow_dispatch:
    inputs:
      release_selection:
        description: 'Select which release to use'
        type: choice
        required: true
        default: 'latest'
        options:
          - latest
          - specific
      release_tag:
        description: 'Release tag (only needed if "specific" is selected above)'
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2.0.0
        with:
          version: 3.39.2
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Create Example Asset Archives
        run: |
          echo "Creating example asset archives for release..."
          GH_TOKEN=${{ secrets.GITHUB_TOKEN }} task -t scripts/Taskfile.examples.yml create-example-asset-archives UPLOAD_TO_RELEASE=true RELEASE_TAG=v${{ github.event.inputs.release_tag }} CLEAN_UP=true
          echo "Example assets created and uploaded to release."