name: Zip and Upload Examples

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Zip each example directory
        run: |
          mkdir -p zips
          for dir in examples/*/ ; do
            name=$(basename "$dir")
            zip -r "zips/${name}.zip" "$dir"
          done

      - name: Get latest release
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const releases = await github.rest.repos.listReleases({
              owner: context.repo.owner,
              repo: context.repo.repo,
              per_page: 1
            });
            if (releases.data.length === 0) {
              throw new Error('No releases found');
            }
            core.setOutput('upload_url', releases.data[0].upload_url);

      - name: Upload zipped examples to latest release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for zip in zips/*.zip; do
            name=$(basename "$zip")
            curl -sSL \
              -X POST \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "Content-Type: application/zip" \
              --data-binary @"$zip" \
              "${{ steps.get_release.outputs.upload_url }}?name=$name"
          done

