name: Zip and Upload Examples

on:
  workflow_dispatch:
    inputs:
      release_selection:
        description: 'Select which release to use'
        type: choice
        required: true
        default: 'latest'
        options:
          - latest
          - specific
      release_tag:
        description: 'Release tag (only needed if "specific" is selected above)'
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  zip-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create Example Asset Archives
        run: |
          echo "Creating example asset archives for release..."
          task -t scripts/Taskfile.examples.yml create-example-asset-archives UPLOAD_TO_RELEASE=true RELEASE_TAG=v${{ github.event.inputs.release_tag }} CLEAN_UP=true
          echo "Example assets created and uploaded to release."