##
# Copyright (C) 2023-2024 Hedera Hashgraph, LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
##

name: "PR Checks"
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

defaults:
  run:
    shell: bash

concurrency:
  group: pr-checks-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  env-vars:
    name: Set Environment Variables
    uses: ./.github/workflows/zxc-env-vars.yaml
    with:
      custom-job-label: Set Environment Variables

  code-style:
    name: Code Style
    uses: ./.github/workflows/zxc-code-style.yaml
    with:
      custom-job-label: Standard

  e2e-tests:
    name: E2E Tests (${{matrix.consensus-node-version }} ${{ matrix.e2e-test-type.name }}})
    if: ${{ !cancelled() && always() }}
    uses: ./.github/workflows/zxc-e2e-test.yaml
    needs:
      - env-vars
      - code-style
    strategy:
      fail-fast: false
      matrix:
        consensus-node-version: ["v0.62.1", "v0.61.4"]
        e2e-test-type:
          - { name: "Node Add", test-script: "test-${{ needs.env-vars.outputs.e2e-node-add-test-subdir }}", coverage-subdirectory: "${{ needs.env-vars.outputs.e2e-node-add-test-subdir }}", coverage-report-name: "${{ needs.env-vars.outputs.e2e-node-add-coverage-report }}", cluster-name: "${{ needs.env-vars.outputs.e2e-node-add-test-subdir }}-${{ github.run_id }}-${{ github.run_attempt }}" }
          - { name: "Node Delete", test-script: "test-${{ needs.env-vars.outputs.e2e-node-delete-test-subdir }}", coverage-subdirectory: "${{ needs.env-vars.outputs.e2e-node-delete-test-subdir }}", coverage-report-name: "${{ needs.env-vars.outputs.e2e-node-delete-coverage-report }}", cluster-name: "${{needs.env-vars.outputs.e2e-node-delete-test-subdir}}-${{ github.run_id }}-${{ github.run_attempt }}" }
          - { name: "Node Update", test-script: "test-${{ needs.env-vars.outputs.e2e-node-update-test-subdir }}", coverage-subdirectory: "${{ needs.env-vars.outputs.e2e-node-update-test-subdir }}", coverage-report-name: "${{ needs.env-vars.outputs.e2e-node-update-coverage-report }}", cluster-name: "${{ needs.env-vars.outputs.e2e-node-update-test-subdir }}-${{ github.run_id }}-${{ github.run_attempt }}" }
      max-parallel: 5
    with:
      custom-job-label: ${{ matrix.e2e-test-type.name }}
      test-script: ${{ matrix.e2e-test-type.test-script }}
      coverage-subdirectory: ${{ matrix.e2e-test-type.coverage-subdirectory }}
      coverage-report-name: ${{ matrix.e2e-test-type.coverage-report-name }}
      cluster-name: ${{ matrix.e2e-test-type.cluster-name }}
      version: ${{ matrix.consensus-node-version }}
